version: 0.2

phases:
  install:
    runtime-versions:
       python: 3.8
    commands: 
      - echo set python runtime version 3.8

  pre_build:
    commands:
      - echo pre_build

  build:
    commands:
      - echo Entered the build phase...
      - echo Build started on `date`
      - pwd
      - cp -R ./cars /dryvr/examples/cars/
      - python3 /dryvr/main.py test.json

artifacts:
  files:
    - '**/*'