version: 0.2

phases:
  install:
    runtime-versions:
       python: 3.8
    commands: 
      - echo set python runtime version 3.8

  pre-build:
    commands:
      - echo install numpy 
      - pip install numpy
  build:
    commands:
      - echo Entered the build phase...
      - echo Build started on `date`
      - python hello_world.py

artifacts:
  files:
    - '**/*'