version: 0.2

phases:
  install:
    runtime-versions:
       python: 3.8
    commands: 
      - echo set python runtime version 3.8

  pre_build:
    commands:
      - echo pre_build
      - ls
      - pwd
  build:
    commands:
      - echo Entered the build phase...
      - echo Build started on `date`
      - python3 main.py input/daginput/input_thermo.json

artifacts:
  files:
    - '**/*'